name: unsigned-dmg-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name:  macOS Build (experimental/unsigned)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
        working-directory: /

      - run: pod repo update
        working-directory: /macOS

      - run: flutter build macOS --release --no-codesign --no-tree-shake-icons
        working-directory: /

      - run: ls
        working-directory: /build/macos/Build/Products/Release/

      - run: mv Runner.app/ Lanis.app/
        working-directory: /build/macos/Build/Products/Release/

      - name: DMG Output
        run: hdiutil create -volname "Lanis" -srcfolder "Lanis.app" -ov -format UDZO "Lanis.dmg"
        working-directory: /build/macos/Build/Products/Release/

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-binary
          path: build/macos/Build/Products/Release/Lanis.dmg
