name: unsigned-dmg-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name:  macOS Build (experimental/unsigned)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get

      - run: dart run intl_utils:generate

      - run: pod repo update
        working-directory: macos

      - run: flutter build macos --release

      - name: DMG Output
        run: hdiutil create -volname "Lanis" -srcfolder "lanis.app" -ov -format UDZO "Lanis.dmg"
        working-directory: build/macos/Build/Products/Release/

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v6
        with:
          name: macos-binary
          path: build/macos/Build/Products/Release/Lanis.dmg
